// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netstat.proto

package org.networkMonitor.message.grpc;

public final class Netstat {
  private Netstat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_networkMonitor_message_grpc_NetstatObj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_networkMonitor_message_grpc_NetstatObj_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_networkMonitor_message_grpc_NetstatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_networkMonitor_message_grpc_NetstatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_networkMonitor_message_grpc_NetstatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_networkMonitor_message_grpc_NetstatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rnetstat.proto\022\037org.networkMonitor.mess" +
      "age.grpc\"\223\001\n\nNetstatObj\022\017\n\007address\030\001 \001(\t" +
      "\022\014\n\004type\030\002 \001(\t\022\r\n\005recvQ\030\003 \001(\t\022\r\n\005sendQ\030\004" +
      " \001(\t\022\r\n\005iNode\030\005 \001(\t\022\014\n\004conn\030\006 \001(\t\022\014\n\004ref" +
      "s\030\007 \001(\t\022\017\n\007nextref\030\010 \001(\t\022\014\n\004addr\030\t \001(\t\"J" +
      "\n\016NetstatRequest\0228\n\003obj\030\001 \003(\0132+.org.netw" +
      "orkMonitor.message.grpc.NetstatObj\"\"\n\017Ne" +
      "tstatResponse\022\017\n\007message\030\001 \001(\t2\204\001\n\016Netst" +
      "atService\022r\n\013SendNetstat\022/.org.networkMo" +
      "nitor.message.grpc.NetstatRequest\0320.org." +
      "networkMonitor.message.grpc.NetstatRespo" +
      "nse\"\000B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_networkMonitor_message_grpc_NetstatObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_networkMonitor_message_grpc_NetstatObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_networkMonitor_message_grpc_NetstatObj_descriptor,
        new java.lang.String[] { "Address", "Type", "RecvQ", "SendQ", "INode", "Conn", "Refs", "Nextref", "Addr", });
    internal_static_org_networkMonitor_message_grpc_NetstatRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_networkMonitor_message_grpc_NetstatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_networkMonitor_message_grpc_NetstatRequest_descriptor,
        new java.lang.String[] { "Obj", });
    internal_static_org_networkMonitor_message_grpc_NetstatResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_networkMonitor_message_grpc_NetstatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_networkMonitor_message_grpc_NetstatResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
