// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netstat.proto

package org.networkMonitor.message.grpc;

public interface NetstatObjOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.networkMonitor.message.grpc.NetstatObj)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string address = 1;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string type = 2;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string recvQ = 3;</code>
   */
  java.lang.String getRecvQ();
  /**
   * <code>string recvQ = 3;</code>
   */
  com.google.protobuf.ByteString
      getRecvQBytes();

  /**
   * <code>string sendQ = 4;</code>
   */
  java.lang.String getSendQ();
  /**
   * <code>string sendQ = 4;</code>
   */
  com.google.protobuf.ByteString
      getSendQBytes();

  /**
   * <code>string iNode = 5;</code>
   */
  java.lang.String getINode();
  /**
   * <code>string iNode = 5;</code>
   */
  com.google.protobuf.ByteString
      getINodeBytes();

  /**
   * <code>string conn = 6;</code>
   */
  java.lang.String getConn();
  /**
   * <code>string conn = 6;</code>
   */
  com.google.protobuf.ByteString
      getConnBytes();

  /**
   * <code>string refs = 7;</code>
   */
  java.lang.String getRefs();
  /**
   * <code>string refs = 7;</code>
   */
  com.google.protobuf.ByteString
      getRefsBytes();

  /**
   * <code>string nextref = 8;</code>
   */
  java.lang.String getNextref();
  /**
   * <code>string nextref = 8;</code>
   */
  com.google.protobuf.ByteString
      getNextrefBytes();

  /**
   * <code>string addr = 9;</code>
   */
  java.lang.String getAddr();
  /**
   * <code>string addr = 9;</code>
   */
  com.google.protobuf.ByteString
      getAddrBytes();
}
