// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netstat.proto

package org.networkMonitor.message.grpc;

/**
 * Protobuf type {@code org.networkMonitor.message.grpc.NetstatObj}
 */
public  final class NetstatObj extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.networkMonitor.message.grpc.NetstatObj)
    NetstatObjOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NetstatObj.newBuilder() to construct.
  private NetstatObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NetstatObj() {
    address_ = "";
    type_ = "";
    recvQ_ = "";
    sendQ_ = "";
    iNode_ = "";
    conn_ = "";
    refs_ = "";
    nextref_ = "";
    addr_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NetstatObj(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            address_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            recvQ_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            sendQ_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            iNode_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            conn_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            refs_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            nextref_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            addr_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.networkMonitor.message.grpc.Netstat.internal_static_org_networkMonitor_message_grpc_NetstatObj_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.networkMonitor.message.grpc.Netstat.internal_static_org_networkMonitor_message_grpc_NetstatObj_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.networkMonitor.message.grpc.NetstatObj.class, org.networkMonitor.message.grpc.NetstatObj.Builder.class);
  }

  public static final int ADDRESS_FIELD_NUMBER = 1;
  private volatile java.lang.Object address_;
  /**
   * <code>string address = 1;</code>
   */
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      address_ = s;
      return s;
    }
  }
  /**
   * <code>string address = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object type_;
  /**
   * <code>string type = 2;</code>
   */
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECVQ_FIELD_NUMBER = 3;
  private volatile java.lang.Object recvQ_;
  /**
   * <code>string recvQ = 3;</code>
   */
  public java.lang.String getRecvQ() {
    java.lang.Object ref = recvQ_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recvQ_ = s;
      return s;
    }
  }
  /**
   * <code>string recvQ = 3;</code>
   */
  public com.google.protobuf.ByteString
      getRecvQBytes() {
    java.lang.Object ref = recvQ_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      recvQ_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENDQ_FIELD_NUMBER = 4;
  private volatile java.lang.Object sendQ_;
  /**
   * <code>string sendQ = 4;</code>
   */
  public java.lang.String getSendQ() {
    java.lang.Object ref = sendQ_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sendQ_ = s;
      return s;
    }
  }
  /**
   * <code>string sendQ = 4;</code>
   */
  public com.google.protobuf.ByteString
      getSendQBytes() {
    java.lang.Object ref = sendQ_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sendQ_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INODE_FIELD_NUMBER = 5;
  private volatile java.lang.Object iNode_;
  /**
   * <code>string iNode = 5;</code>
   */
  public java.lang.String getINode() {
    java.lang.Object ref = iNode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      iNode_ = s;
      return s;
    }
  }
  /**
   * <code>string iNode = 5;</code>
   */
  public com.google.protobuf.ByteString
      getINodeBytes() {
    java.lang.Object ref = iNode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      iNode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONN_FIELD_NUMBER = 6;
  private volatile java.lang.Object conn_;
  /**
   * <code>string conn = 6;</code>
   */
  public java.lang.String getConn() {
    java.lang.Object ref = conn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      conn_ = s;
      return s;
    }
  }
  /**
   * <code>string conn = 6;</code>
   */
  public com.google.protobuf.ByteString
      getConnBytes() {
    java.lang.Object ref = conn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      conn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REFS_FIELD_NUMBER = 7;
  private volatile java.lang.Object refs_;
  /**
   * <code>string refs = 7;</code>
   */
  public java.lang.String getRefs() {
    java.lang.Object ref = refs_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      refs_ = s;
      return s;
    }
  }
  /**
   * <code>string refs = 7;</code>
   */
  public com.google.protobuf.ByteString
      getRefsBytes() {
    java.lang.Object ref = refs_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      refs_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEXTREF_FIELD_NUMBER = 8;
  private volatile java.lang.Object nextref_;
  /**
   * <code>string nextref = 8;</code>
   */
  public java.lang.String getNextref() {
    java.lang.Object ref = nextref_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nextref_ = s;
      return s;
    }
  }
  /**
   * <code>string nextref = 8;</code>
   */
  public com.google.protobuf.ByteString
      getNextrefBytes() {
    java.lang.Object ref = nextref_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nextref_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDR_FIELD_NUMBER = 9;
  private volatile java.lang.Object addr_;
  /**
   * <code>string addr = 9;</code>
   */
  public java.lang.String getAddr() {
    java.lang.Object ref = addr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      addr_ = s;
      return s;
    }
  }
  /**
   * <code>string addr = 9;</code>
   */
  public com.google.protobuf.ByteString
      getAddrBytes() {
    java.lang.Object ref = addr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      addr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
    }
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
    }
    if (!getRecvQBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, recvQ_);
    }
    if (!getSendQBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sendQ_);
    }
    if (!getINodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, iNode_);
    }
    if (!getConnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, conn_);
    }
    if (!getRefsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, refs_);
    }
    if (!getNextrefBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, nextref_);
    }
    if (!getAddrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, addr_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
    }
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
    }
    if (!getRecvQBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, recvQ_);
    }
    if (!getSendQBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sendQ_);
    }
    if (!getINodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, iNode_);
    }
    if (!getConnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, conn_);
    }
    if (!getRefsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, refs_);
    }
    if (!getNextrefBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, nextref_);
    }
    if (!getAddrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, addr_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.networkMonitor.message.grpc.NetstatObj)) {
      return super.equals(obj);
    }
    org.networkMonitor.message.grpc.NetstatObj other = (org.networkMonitor.message.grpc.NetstatObj) obj;

    boolean result = true;
    result = result && getAddress()
        .equals(other.getAddress());
    result = result && getType()
        .equals(other.getType());
    result = result && getRecvQ()
        .equals(other.getRecvQ());
    result = result && getSendQ()
        .equals(other.getSendQ());
    result = result && getINode()
        .equals(other.getINode());
    result = result && getConn()
        .equals(other.getConn());
    result = result && getRefs()
        .equals(other.getRefs());
    result = result && getNextref()
        .equals(other.getNextref());
    result = result && getAddr()
        .equals(other.getAddr());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getAddress().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + RECVQ_FIELD_NUMBER;
    hash = (53 * hash) + getRecvQ().hashCode();
    hash = (37 * hash) + SENDQ_FIELD_NUMBER;
    hash = (53 * hash) + getSendQ().hashCode();
    hash = (37 * hash) + INODE_FIELD_NUMBER;
    hash = (53 * hash) + getINode().hashCode();
    hash = (37 * hash) + CONN_FIELD_NUMBER;
    hash = (53 * hash) + getConn().hashCode();
    hash = (37 * hash) + REFS_FIELD_NUMBER;
    hash = (53 * hash) + getRefs().hashCode();
    hash = (37 * hash) + NEXTREF_FIELD_NUMBER;
    hash = (53 * hash) + getNextref().hashCode();
    hash = (37 * hash) + ADDR_FIELD_NUMBER;
    hash = (53 * hash) + getAddr().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.networkMonitor.message.grpc.NetstatObj parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.networkMonitor.message.grpc.NetstatObj parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.networkMonitor.message.grpc.NetstatObj parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.networkMonitor.message.grpc.NetstatObj parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.networkMonitor.message.grpc.NetstatObj parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.networkMonitor.message.grpc.NetstatObj parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.networkMonitor.message.grpc.NetstatObj parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.networkMonitor.message.grpc.NetstatObj parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.networkMonitor.message.grpc.NetstatObj parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.networkMonitor.message.grpc.NetstatObj parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.networkMonitor.message.grpc.NetstatObj parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.networkMonitor.message.grpc.NetstatObj parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.networkMonitor.message.grpc.NetstatObj prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.networkMonitor.message.grpc.NetstatObj}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.networkMonitor.message.grpc.NetstatObj)
      org.networkMonitor.message.grpc.NetstatObjOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.networkMonitor.message.grpc.Netstat.internal_static_org_networkMonitor_message_grpc_NetstatObj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.networkMonitor.message.grpc.Netstat.internal_static_org_networkMonitor_message_grpc_NetstatObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.networkMonitor.message.grpc.NetstatObj.class, org.networkMonitor.message.grpc.NetstatObj.Builder.class);
    }

    // Construct using org.networkMonitor.message.grpc.NetstatObj.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      address_ = "";

      type_ = "";

      recvQ_ = "";

      sendQ_ = "";

      iNode_ = "";

      conn_ = "";

      refs_ = "";

      nextref_ = "";

      addr_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.networkMonitor.message.grpc.Netstat.internal_static_org_networkMonitor_message_grpc_NetstatObj_descriptor;
    }

    @java.lang.Override
    public org.networkMonitor.message.grpc.NetstatObj getDefaultInstanceForType() {
      return org.networkMonitor.message.grpc.NetstatObj.getDefaultInstance();
    }

    @java.lang.Override
    public org.networkMonitor.message.grpc.NetstatObj build() {
      org.networkMonitor.message.grpc.NetstatObj result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.networkMonitor.message.grpc.NetstatObj buildPartial() {
      org.networkMonitor.message.grpc.NetstatObj result = new org.networkMonitor.message.grpc.NetstatObj(this);
      result.address_ = address_;
      result.type_ = type_;
      result.recvQ_ = recvQ_;
      result.sendQ_ = sendQ_;
      result.iNode_ = iNode_;
      result.conn_ = conn_;
      result.refs_ = refs_;
      result.nextref_ = nextref_;
      result.addr_ = addr_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.networkMonitor.message.grpc.NetstatObj) {
        return mergeFrom((org.networkMonitor.message.grpc.NetstatObj)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.networkMonitor.message.grpc.NetstatObj other) {
      if (other == org.networkMonitor.message.grpc.NetstatObj.getDefaultInstance()) return this;
      if (!other.getAddress().isEmpty()) {
        address_ = other.address_;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (!other.getRecvQ().isEmpty()) {
        recvQ_ = other.recvQ_;
        onChanged();
      }
      if (!other.getSendQ().isEmpty()) {
        sendQ_ = other.sendQ_;
        onChanged();
      }
      if (!other.getINode().isEmpty()) {
        iNode_ = other.iNode_;
        onChanged();
      }
      if (!other.getConn().isEmpty()) {
        conn_ = other.conn_;
        onChanged();
      }
      if (!other.getRefs().isEmpty()) {
        refs_ = other.refs_;
        onChanged();
      }
      if (!other.getNextref().isEmpty()) {
        nextref_ = other.nextref_;
        onChanged();
      }
      if (!other.getAddr().isEmpty()) {
        addr_ = other.addr_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.networkMonitor.message.grpc.NetstatObj parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.networkMonitor.message.grpc.NetstatObj) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object address_ = "";
    /**
     * <code>string address = 1;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string address = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string address = 1;</code>
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string address = 1;</code>
     */
    public Builder clearAddress() {
      
      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string address = 1;</code>
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      address_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 2;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 2;</code>
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 2;</code>
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>string type = 2;</code>
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object recvQ_ = "";
    /**
     * <code>string recvQ = 3;</code>
     */
    public java.lang.String getRecvQ() {
      java.lang.Object ref = recvQ_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recvQ_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string recvQ = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRecvQBytes() {
      java.lang.Object ref = recvQ_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recvQ_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string recvQ = 3;</code>
     */
    public Builder setRecvQ(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      recvQ_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string recvQ = 3;</code>
     */
    public Builder clearRecvQ() {
      
      recvQ_ = getDefaultInstance().getRecvQ();
      onChanged();
      return this;
    }
    /**
     * <code>string recvQ = 3;</code>
     */
    public Builder setRecvQBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      recvQ_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sendQ_ = "";
    /**
     * <code>string sendQ = 4;</code>
     */
    public java.lang.String getSendQ() {
      java.lang.Object ref = sendQ_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sendQ_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sendQ = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSendQBytes() {
      java.lang.Object ref = sendQ_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sendQ_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sendQ = 4;</code>
     */
    public Builder setSendQ(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sendQ_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sendQ = 4;</code>
     */
    public Builder clearSendQ() {
      
      sendQ_ = getDefaultInstance().getSendQ();
      onChanged();
      return this;
    }
    /**
     * <code>string sendQ = 4;</code>
     */
    public Builder setSendQBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sendQ_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object iNode_ = "";
    /**
     * <code>string iNode = 5;</code>
     */
    public java.lang.String getINode() {
      java.lang.Object ref = iNode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iNode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string iNode = 5;</code>
     */
    public com.google.protobuf.ByteString
        getINodeBytes() {
      java.lang.Object ref = iNode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iNode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string iNode = 5;</code>
     */
    public Builder setINode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      iNode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string iNode = 5;</code>
     */
    public Builder clearINode() {
      
      iNode_ = getDefaultInstance().getINode();
      onChanged();
      return this;
    }
    /**
     * <code>string iNode = 5;</code>
     */
    public Builder setINodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      iNode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object conn_ = "";
    /**
     * <code>string conn = 6;</code>
     */
    public java.lang.String getConn() {
      java.lang.Object ref = conn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        conn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string conn = 6;</code>
     */
    public com.google.protobuf.ByteString
        getConnBytes() {
      java.lang.Object ref = conn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string conn = 6;</code>
     */
    public Builder setConn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      conn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string conn = 6;</code>
     */
    public Builder clearConn() {
      
      conn_ = getDefaultInstance().getConn();
      onChanged();
      return this;
    }
    /**
     * <code>string conn = 6;</code>
     */
    public Builder setConnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      conn_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object refs_ = "";
    /**
     * <code>string refs = 7;</code>
     */
    public java.lang.String getRefs() {
      java.lang.Object ref = refs_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        refs_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string refs = 7;</code>
     */
    public com.google.protobuf.ByteString
        getRefsBytes() {
      java.lang.Object ref = refs_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string refs = 7;</code>
     */
    public Builder setRefs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      refs_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string refs = 7;</code>
     */
    public Builder clearRefs() {
      
      refs_ = getDefaultInstance().getRefs();
      onChanged();
      return this;
    }
    /**
     * <code>string refs = 7;</code>
     */
    public Builder setRefsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      refs_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nextref_ = "";
    /**
     * <code>string nextref = 8;</code>
     */
    public java.lang.String getNextref() {
      java.lang.Object ref = nextref_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nextref_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nextref = 8;</code>
     */
    public com.google.protobuf.ByteString
        getNextrefBytes() {
      java.lang.Object ref = nextref_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nextref_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nextref = 8;</code>
     */
    public Builder setNextref(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nextref_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nextref = 8;</code>
     */
    public Builder clearNextref() {
      
      nextref_ = getDefaultInstance().getNextref();
      onChanged();
      return this;
    }
    /**
     * <code>string nextref = 8;</code>
     */
    public Builder setNextrefBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nextref_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object addr_ = "";
    /**
     * <code>string addr = 9;</code>
     */
    public java.lang.String getAddr() {
      java.lang.Object ref = addr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string addr = 9;</code>
     */
    public com.google.protobuf.ByteString
        getAddrBytes() {
      java.lang.Object ref = addr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string addr = 9;</code>
     */
    public Builder setAddr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      addr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string addr = 9;</code>
     */
    public Builder clearAddr() {
      
      addr_ = getDefaultInstance().getAddr();
      onChanged();
      return this;
    }
    /**
     * <code>string addr = 9;</code>
     */
    public Builder setAddrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      addr_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.networkMonitor.message.grpc.NetstatObj)
  }

  // @@protoc_insertion_point(class_scope:org.networkMonitor.message.grpc.NetstatObj)
  private static final org.networkMonitor.message.grpc.NetstatObj DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.networkMonitor.message.grpc.NetstatObj();
  }

  public static org.networkMonitor.message.grpc.NetstatObj getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NetstatObj>
      PARSER = new com.google.protobuf.AbstractParser<NetstatObj>() {
    @java.lang.Override
    public NetstatObj parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NetstatObj(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NetstatObj> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NetstatObj> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.networkMonitor.message.grpc.NetstatObj getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

