// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netstat.proto

package org.networkMonitor.message.grpc;

public interface NetstatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.networkMonitor.message.grpc.NetstatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
   */
  java.util.List<org.networkMonitor.message.grpc.NetstatObj> 
      getObjList();
  /**
   * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
   */
  org.networkMonitor.message.grpc.NetstatObj getObj(int index);
  /**
   * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
   */
  int getObjCount();
  /**
   * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
   */
  java.util.List<? extends org.networkMonitor.message.grpc.NetstatObjOrBuilder> 
      getObjOrBuilderList();
  /**
   * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
   */
  org.networkMonitor.message.grpc.NetstatObjOrBuilder getObjOrBuilder(
      int index);
}
