// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netstat.proto

package org.networkMonitor.message.grpc;

/**
 * Protobuf type {@code org.networkMonitor.message.grpc.NetstatRequest}
 */
public  final class NetstatRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.networkMonitor.message.grpc.NetstatRequest)
    NetstatRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NetstatRequest.newBuilder() to construct.
  private NetstatRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NetstatRequest() {
    obj_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NetstatRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              obj_ = new java.util.ArrayList<org.networkMonitor.message.grpc.NetstatObj>();
              mutable_bitField0_ |= 0x00000001;
            }
            obj_.add(
                input.readMessage(org.networkMonitor.message.grpc.NetstatObj.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        obj_ = java.util.Collections.unmodifiableList(obj_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.networkMonitor.message.grpc.Netstat.internal_static_org_networkMonitor_message_grpc_NetstatRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.networkMonitor.message.grpc.Netstat.internal_static_org_networkMonitor_message_grpc_NetstatRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.networkMonitor.message.grpc.NetstatRequest.class, org.networkMonitor.message.grpc.NetstatRequest.Builder.class);
  }

  public static final int OBJ_FIELD_NUMBER = 1;
  private java.util.List<org.networkMonitor.message.grpc.NetstatObj> obj_;
  /**
   * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
   */
  public java.util.List<org.networkMonitor.message.grpc.NetstatObj> getObjList() {
    return obj_;
  }
  /**
   * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
   */
  public java.util.List<? extends org.networkMonitor.message.grpc.NetstatObjOrBuilder> 
      getObjOrBuilderList() {
    return obj_;
  }
  /**
   * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
   */
  public int getObjCount() {
    return obj_.size();
  }
  /**
   * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
   */
  public org.networkMonitor.message.grpc.NetstatObj getObj(int index) {
    return obj_.get(index);
  }
  /**
   * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
   */
  public org.networkMonitor.message.grpc.NetstatObjOrBuilder getObjOrBuilder(
      int index) {
    return obj_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < obj_.size(); i++) {
      output.writeMessage(1, obj_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < obj_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, obj_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.networkMonitor.message.grpc.NetstatRequest)) {
      return super.equals(obj);
    }
    org.networkMonitor.message.grpc.NetstatRequest other = (org.networkMonitor.message.grpc.NetstatRequest) obj;

    boolean result = true;
    result = result && getObjList()
        .equals(other.getObjList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getObjCount() > 0) {
      hash = (37 * hash) + OBJ_FIELD_NUMBER;
      hash = (53 * hash) + getObjList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.networkMonitor.message.grpc.NetstatRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.networkMonitor.message.grpc.NetstatRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.networkMonitor.message.grpc.NetstatRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.networkMonitor.message.grpc.NetstatRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.networkMonitor.message.grpc.NetstatRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.networkMonitor.message.grpc.NetstatRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.networkMonitor.message.grpc.NetstatRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.networkMonitor.message.grpc.NetstatRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.networkMonitor.message.grpc.NetstatRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.networkMonitor.message.grpc.NetstatRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.networkMonitor.message.grpc.NetstatRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.networkMonitor.message.grpc.NetstatRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.networkMonitor.message.grpc.NetstatRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.networkMonitor.message.grpc.NetstatRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.networkMonitor.message.grpc.NetstatRequest)
      org.networkMonitor.message.grpc.NetstatRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.networkMonitor.message.grpc.Netstat.internal_static_org_networkMonitor_message_grpc_NetstatRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.networkMonitor.message.grpc.Netstat.internal_static_org_networkMonitor_message_grpc_NetstatRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.networkMonitor.message.grpc.NetstatRequest.class, org.networkMonitor.message.grpc.NetstatRequest.Builder.class);
    }

    // Construct using org.networkMonitor.message.grpc.NetstatRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getObjFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (objBuilder_ == null) {
        obj_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        objBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.networkMonitor.message.grpc.Netstat.internal_static_org_networkMonitor_message_grpc_NetstatRequest_descriptor;
    }

    @java.lang.Override
    public org.networkMonitor.message.grpc.NetstatRequest getDefaultInstanceForType() {
      return org.networkMonitor.message.grpc.NetstatRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.networkMonitor.message.grpc.NetstatRequest build() {
      org.networkMonitor.message.grpc.NetstatRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.networkMonitor.message.grpc.NetstatRequest buildPartial() {
      org.networkMonitor.message.grpc.NetstatRequest result = new org.networkMonitor.message.grpc.NetstatRequest(this);
      int from_bitField0_ = bitField0_;
      if (objBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          obj_ = java.util.Collections.unmodifiableList(obj_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.obj_ = obj_;
      } else {
        result.obj_ = objBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.networkMonitor.message.grpc.NetstatRequest) {
        return mergeFrom((org.networkMonitor.message.grpc.NetstatRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.networkMonitor.message.grpc.NetstatRequest other) {
      if (other == org.networkMonitor.message.grpc.NetstatRequest.getDefaultInstance()) return this;
      if (objBuilder_ == null) {
        if (!other.obj_.isEmpty()) {
          if (obj_.isEmpty()) {
            obj_ = other.obj_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureObjIsMutable();
            obj_.addAll(other.obj_);
          }
          onChanged();
        }
      } else {
        if (!other.obj_.isEmpty()) {
          if (objBuilder_.isEmpty()) {
            objBuilder_.dispose();
            objBuilder_ = null;
            obj_ = other.obj_;
            bitField0_ = (bitField0_ & ~0x00000001);
            objBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getObjFieldBuilder() : null;
          } else {
            objBuilder_.addAllMessages(other.obj_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.networkMonitor.message.grpc.NetstatRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.networkMonitor.message.grpc.NetstatRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.networkMonitor.message.grpc.NetstatObj> obj_ =
      java.util.Collections.emptyList();
    private void ensureObjIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        obj_ = new java.util.ArrayList<org.networkMonitor.message.grpc.NetstatObj>(obj_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.networkMonitor.message.grpc.NetstatObj, org.networkMonitor.message.grpc.NetstatObj.Builder, org.networkMonitor.message.grpc.NetstatObjOrBuilder> objBuilder_;

    /**
     * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
     */
    public java.util.List<org.networkMonitor.message.grpc.NetstatObj> getObjList() {
      if (objBuilder_ == null) {
        return java.util.Collections.unmodifiableList(obj_);
      } else {
        return objBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
     */
    public int getObjCount() {
      if (objBuilder_ == null) {
        return obj_.size();
      } else {
        return objBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
     */
    public org.networkMonitor.message.grpc.NetstatObj getObj(int index) {
      if (objBuilder_ == null) {
        return obj_.get(index);
      } else {
        return objBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
     */
    public Builder setObj(
        int index, org.networkMonitor.message.grpc.NetstatObj value) {
      if (objBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureObjIsMutable();
        obj_.set(index, value);
        onChanged();
      } else {
        objBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
     */
    public Builder setObj(
        int index, org.networkMonitor.message.grpc.NetstatObj.Builder builderForValue) {
      if (objBuilder_ == null) {
        ensureObjIsMutable();
        obj_.set(index, builderForValue.build());
        onChanged();
      } else {
        objBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
     */
    public Builder addObj(org.networkMonitor.message.grpc.NetstatObj value) {
      if (objBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureObjIsMutable();
        obj_.add(value);
        onChanged();
      } else {
        objBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
     */
    public Builder addObj(
        int index, org.networkMonitor.message.grpc.NetstatObj value) {
      if (objBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureObjIsMutable();
        obj_.add(index, value);
        onChanged();
      } else {
        objBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
     */
    public Builder addObj(
        org.networkMonitor.message.grpc.NetstatObj.Builder builderForValue) {
      if (objBuilder_ == null) {
        ensureObjIsMutable();
        obj_.add(builderForValue.build());
        onChanged();
      } else {
        objBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
     */
    public Builder addObj(
        int index, org.networkMonitor.message.grpc.NetstatObj.Builder builderForValue) {
      if (objBuilder_ == null) {
        ensureObjIsMutable();
        obj_.add(index, builderForValue.build());
        onChanged();
      } else {
        objBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
     */
    public Builder addAllObj(
        java.lang.Iterable<? extends org.networkMonitor.message.grpc.NetstatObj> values) {
      if (objBuilder_ == null) {
        ensureObjIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, obj_);
        onChanged();
      } else {
        objBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
     */
    public Builder clearObj() {
      if (objBuilder_ == null) {
        obj_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        objBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
     */
    public Builder removeObj(int index) {
      if (objBuilder_ == null) {
        ensureObjIsMutable();
        obj_.remove(index);
        onChanged();
      } else {
        objBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
     */
    public org.networkMonitor.message.grpc.NetstatObj.Builder getObjBuilder(
        int index) {
      return getObjFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
     */
    public org.networkMonitor.message.grpc.NetstatObjOrBuilder getObjOrBuilder(
        int index) {
      if (objBuilder_ == null) {
        return obj_.get(index);  } else {
        return objBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
     */
    public java.util.List<? extends org.networkMonitor.message.grpc.NetstatObjOrBuilder> 
         getObjOrBuilderList() {
      if (objBuilder_ != null) {
        return objBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(obj_);
      }
    }
    /**
     * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
     */
    public org.networkMonitor.message.grpc.NetstatObj.Builder addObjBuilder() {
      return getObjFieldBuilder().addBuilder(
          org.networkMonitor.message.grpc.NetstatObj.getDefaultInstance());
    }
    /**
     * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
     */
    public org.networkMonitor.message.grpc.NetstatObj.Builder addObjBuilder(
        int index) {
      return getObjFieldBuilder().addBuilder(
          index, org.networkMonitor.message.grpc.NetstatObj.getDefaultInstance());
    }
    /**
     * <code>repeated .org.networkMonitor.message.grpc.NetstatObj obj = 1;</code>
     */
    public java.util.List<org.networkMonitor.message.grpc.NetstatObj.Builder> 
         getObjBuilderList() {
      return getObjFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.networkMonitor.message.grpc.NetstatObj, org.networkMonitor.message.grpc.NetstatObj.Builder, org.networkMonitor.message.grpc.NetstatObjOrBuilder> 
        getObjFieldBuilder() {
      if (objBuilder_ == null) {
        objBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.networkMonitor.message.grpc.NetstatObj, org.networkMonitor.message.grpc.NetstatObj.Builder, org.networkMonitor.message.grpc.NetstatObjOrBuilder>(
                obj_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        obj_ = null;
      }
      return objBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.networkMonitor.message.grpc.NetstatRequest)
  }

  // @@protoc_insertion_point(class_scope:org.networkMonitor.message.grpc.NetstatRequest)
  private static final org.networkMonitor.message.grpc.NetstatRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.networkMonitor.message.grpc.NetstatRequest();
  }

  public static org.networkMonitor.message.grpc.NetstatRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NetstatRequest>
      PARSER = new com.google.protobuf.AbstractParser<NetstatRequest>() {
    @java.lang.Override
    public NetstatRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NetstatRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NetstatRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NetstatRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.networkMonitor.message.grpc.NetstatRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

